version: '3.9'

services:

  redis:
    image: "redis"
    ports:
        - "6379:6379"

  mssql:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "127.0.0.1:1423:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A!VeryComplex123Password

  mymindset.cache.webapi:
    image: ${DOCKER_REGISTRY-}mymindsetcachewebapi
    build:
      context: .
      dockerfile: MyMindset.Cache.WebAPI/Dockerfile

